/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Candidate {
  'id' : Principal,
  'bio' : string,
  'name' : string,
  'constituency' : string,
  'photo' : [] | [ExternalBlob],
}
export type ExternalBlob = Uint8Array;
export interface Mla {
  'id' : Principal,
  'bio' : string,
  'name' : string,
  'constituency' : string,
  'photo' : [] | [ExternalBlob],
}
export interface Supporter {
  'id' : Principal,
  'name' : string,
  'address' : string,
  'phone' : string,
  'photo' : [] | [ExternalBlob],
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addCandidate' : ActorMethod<[string, Candidate], undefined>,
  'addMla' : ActorMethod<[string, Mla], undefined>,
  'addSupporter' : ActorMethod<[Supporter], undefined>,
  'adminLogin' : ActorMethod<[string, string], string>,
  'deleteCandidate' : ActorMethod<[string, Principal], undefined>,
  'deleteMla' : ActorMethod<[string, Principal], undefined>,
  'deleteSupporter' : ActorMethod<[string, Principal], undefined>,
  'getAllCandidates' : ActorMethod<[], Array<Candidate>>,
  'getAllMlas' : ActorMethod<[], Array<Mla>>,
  'getAllSupporters' : ActorMethod<[], Array<Supporter>>,
  'updateCandidate' : ActorMethod<[string, Candidate], undefined>,
  'updateMla' : ActorMethod<[string, Mla], undefined>,
  'updateSupporter' : ActorMethod<[string, Supporter], undefined>,
  'verifyAdmin' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];