/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Candidate = IDL.Record({
  'id' : IDL.Principal,
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'constituency' : IDL.Text,
  'photo' : IDL.Opt(ExternalBlob),
});
export const Mla = IDL.Record({
  'id' : IDL.Principal,
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'constituency' : IDL.Text,
  'photo' : IDL.Opt(ExternalBlob),
});
export const Supporter = IDL.Record({
  'id' : IDL.Principal,
  'name' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'photo' : IDL.Opt(ExternalBlob),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addCandidate' : IDL.Func([IDL.Text, Candidate], [], []),
  'addMla' : IDL.Func([IDL.Text, Mla], [], []),
  'addSupporter' : IDL.Func([Supporter], [], []),
  'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'deleteCandidate' : IDL.Func([IDL.Text, IDL.Principal], [], []),
  'deleteMla' : IDL.Func([IDL.Text, IDL.Principal], [], []),
  'deleteSupporter' : IDL.Func([IDL.Text, IDL.Principal], [], []),
  'getAllCandidates' : IDL.Func([], [IDL.Vec(Candidate)], ['query']),
  'getAllMlas' : IDL.Func([], [IDL.Vec(Mla)], ['query']),
  'getAllSupporters' : IDL.Func([], [IDL.Vec(Supporter)], ['query']),
  'updateCandidate' : IDL.Func([IDL.Text, Candidate], [], []),
  'updateMla' : IDL.Func([IDL.Text, Mla], [], []),
  'updateSupporter' : IDL.Func([IDL.Text, Supporter], [], []),
  'verifyAdmin' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Candidate = IDL.Record({
    'id' : IDL.Principal,
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'constituency' : IDL.Text,
    'photo' : IDL.Opt(ExternalBlob),
  });
  const Mla = IDL.Record({
    'id' : IDL.Principal,
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'constituency' : IDL.Text,
    'photo' : IDL.Opt(ExternalBlob),
  });
  const Supporter = IDL.Record({
    'id' : IDL.Principal,
    'name' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'photo' : IDL.Opt(ExternalBlob),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addCandidate' : IDL.Func([IDL.Text, Candidate], [], []),
    'addMla' : IDL.Func([IDL.Text, Mla], [], []),
    'addSupporter' : IDL.Func([Supporter], [], []),
    'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'deleteCandidate' : IDL.Func([IDL.Text, IDL.Principal], [], []),
    'deleteMla' : IDL.Func([IDL.Text, IDL.Principal], [], []),
    'deleteSupporter' : IDL.Func([IDL.Text, IDL.Principal], [], []),
    'getAllCandidates' : IDL.Func([], [IDL.Vec(Candidate)], ['query']),
    'getAllMlas' : IDL.Func([], [IDL.Vec(Mla)], ['query']),
    'getAllSupporters' : IDL.Func([], [IDL.Vec(Supporter)], ['query']),
    'updateCandidate' : IDL.Func([IDL.Text, Candidate], [], []),
    'updateMla' : IDL.Func([IDL.Text, Mla], [], []),
    'updateSupporter' : IDL.Func([IDL.Text, Supporter], [], []),
    'verifyAdmin' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };